### ISSUE TITLE
Error in SvelteKit / Vite project

### ISSUE THREAD

**Issue by aral** [parkingboss/camera#1]
After installing, importing and instantiating the camera, I’m getting:

```
[vite]: Rollup failed to resolve import "web-worker:./qr-worker" from "node_modules/@parkingboss/camera/src/barcode.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
> [vite]: Rollup failed to resolve import "web-worker:./qr-worker" from "node_modules/@parkingboss/camera/src/barcode.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

In latest SvelteKit, which uses Vite.

**Comment by Crisfole** [comment]
@aral Thrilled to see you using this! I'm so sorry we missed this.

We haven't used this one for a long time - our camera usage evolved over time and this was one of several early experiments.

Our latest repo `@parkingboss/barcam` is in prod, although we're updating it to fix some issues that cropped up in iOS 15 only, it's a fairly large API change.
